export { Navbar} from "./navbar/Navbar"
export {HotelCard} from "./HotelCard/HotelCard"
export {Categories} from "./Categories/Categories"
export {HotelImages} from "./HotelImages/HotelImages"
export {HotelDetails} from "./HotelDetails/HotelDetails"
export {FinalPrice} from "./FinalPrice/FinalPrice"